In [45]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KDTree

In [80]:
XEXAMPLE = np.array([[1,1],[2,2], [3,3]])  # 3 points in 2 dimensions
treeEXAMPLE = KDTree(XEXAMPLE, metric='l1')                                         # !!!
distEXAMPLE, indEXAMPLE = treeEXAMPLE.query([[1.25, 1.35]], k=2)
print(indEXAMPLE)  # indices of 2 closest neighbors
print(distEXAMPLE)  # distances to 2 closest neighbors

[[0 1]]
[[0.6 1.4]]


In [8]:
# Define the headers since the data does not have any
headers = ["symboling", "normalized_losses", "make", "fuel_type", "aspiration",
           "num_doors", "body_style", "drive_wheels", "engine_location",
           "wheel_base", "length", "width", "height", "curb_weight",
           "engine_type", "num_cylinders", "engine_size", "fuel_system",
           "bore", "stroke", "compression_ratio", "horsepower", "peak_rpm",
           "city_mpg", "highway_mpg", "price"]

# Read in the CSV file and convert "?" to NaN
df = pd.read_csv("C:/Users/btspanswick/Desktop/PYproject/data/cars.csv",
                  header=None, names=headers, na_values="?" )
df.head()

symboling  normalized_losses         make fuel_type aspiration num_doors  \
0          3                NaN  alfa-romero       gas        std       two   
1          3                NaN  alfa-romero       gas        std       two   
2          1                NaN  alfa-romero       gas        std       two   
3          2              164.0         audi       gas        std      four   
4          2              164.0         audi       gas        std      four   

    body_style drive_wheels engine_location  wheel_base   ...     engine_size  \
0  convertible          rwd           front        88.6   ...             130   
1  convertible          rwd           front        88.6   ...             130   
2    hatchback          rwd           front        94.5   ...             152   
3        sedan          fwd           front        99.8   ...             109   
4        sedan          4wd           front        99.4   ...             136   

   fuel_system  bore  stroke compression_ratio horsepower  peak_rpm city_mpg  \
0         mpfi  3.47    2.68               9.0      111.0    5000.0       21   
1         mpfi  3.47    2.68               9.0      111.0    5000.0       21   
2         mpfi  2.68    3.47               9.0      154.0    5000.0       19   
3         mpfi  3.19    3.40              10.0      102.0    5500.0       24   
4         mpfi  3.19    3.40               8.0      115.0    5500.0       18   

   highway_mpg    price  
0           27  13495.0  
1           27  16500.0  
2           26  16500.0  
3           30  13950.0  
4           22  17450.0  

[5 rows x 26 columns]

In [9]:
df.dtypes

symboling              int64
normalized_losses    float64
make                  object
fuel_type             object
aspiration            object
num_doors             object
body_style            object
drive_wheels          object
engine_location       object
wheel_base           float64
length               float64
width                float64
height               float64
curb_weight            int64
engine_type           object
num_cylinders         object
engine_size            int64
fuel_system           object
bore                 float64
stroke               float64
compression_ratio    float64
horsepower           float64
peak_rpm             float64
city_mpg               int64
highway_mpg            int64
price                float64
dtype: object

In [14]:
obj_df = df.select_dtypes(include=['object']).copy()
other_df = df.select_dtypes(include=['float64','int64']).copy()
obj_df.head()
other_df.head()

symboling  normalized_losses  wheel_base  length  width  height  \
0          3                NaN        88.6   168.8   64.1    48.8   
1          3                NaN        88.6   168.8   64.1    48.8   
2          1                NaN        94.5   171.2   65.5    52.4   
3          2              164.0        99.8   176.6   66.2    54.3   
4          2              164.0        99.4   176.6   66.4    54.3   

   curb_weight  engine_size  bore  stroke  compression_ratio  horsepower  \
0         2548          130  3.47    2.68                9.0       111.0   
1         2548          130  3.47    2.68                9.0       111.0   
2         2823          152  2.68    3.47                9.0       154.0   
3         2337          109  3.19    3.40               10.0       102.0   
4         2824          136  3.19    3.40                8.0       115.0   

   peak_rpm  city_mpg  highway_mpg    price  
0    5000.0        21           27  13495.0  
1    5000.0        21           27  16500.0  
2    5000.0        19           26  16500.0  
3    5500.0        24           30  13950.0  
4    5500.0        18           22  17450.0

In [37]:
dummy_df = pd.get_dummies(obj_df)

In [39]:
cars_dummy = other_df.join(dummy_df)
cars_dummy.head()

symboling  normalized_losses  wheel_base  length  width  height  \
0          3                NaN        88.6   168.8   64.1    48.8   
1          3                NaN        88.6   168.8   64.1    48.8   
2          1                NaN        94.5   171.2   65.5    52.4   
3          2              164.0        99.8   176.6   66.2    54.3   
4          2              164.0        99.4   176.6   66.4    54.3   

   curb_weight  engine_size  bore  stroke        ...         \
0         2548          130  3.47    2.68        ...          
1         2548          130  3.47    2.68        ...          
2         2823          152  2.68    3.47        ...          
3         2337          109  3.19    3.40        ...          
4         2824          136  3.19    3.40        ...          

   num_cylinders_twelve  num_cylinders_two  fuel_system_1bbl  \
0                     0                  0                 0   
1                     0                  0                 0   
2                     0                  0                 0   
3                     0                  0                 0   
4                     0                  0                 0   

   fuel_system_2bbl  fuel_system_4bbl  fuel_system_idi  fuel_system_mfi  \
0                 0                 0                0                0   
1                 0                 0                0                0   
2                 0                 0                0                0   
3                 0                 0                0                0   
4                 0                 0                0                0   

   fuel_system_mpfi  fuel_system_spdi  fuel_system_spfi  
0                 1                 0                 0  
1                 1                 0                 0  
2                 1                 0                 0  
3                 1                 0                 0  
4                 1                 0                 0  

[5 rows x 76 columns]

In [40]:
cars_dummy

symboling  normalized_losses  wheel_base  length  width  height  \
0            3                NaN        88.6   168.8   64.1    48.8   
1            3                NaN        88.6   168.8   64.1    48.8   
2            1                NaN        94.5   171.2   65.5    52.4   
3            2              164.0        99.8   176.6   66.2    54.3   
4            2              164.0        99.4   176.6   66.4    54.3   
5            2                NaN        99.8   177.3   66.3    53.1   
6            1              158.0       105.8   192.7   71.4    55.7   
7            1                NaN       105.8   192.7   71.4    55.7   
8            1              158.0       105.8   192.7   71.4    55.9   
9            0                NaN        99.5   178.2   67.9    52.0   
10           2              192.0       101.2   176.8   64.8    54.3   
11           0              192.0       101.2   176.8   64.8    54.3   
12           0              188.0       101.2   176.8   64.8    54.3   
13           0              188.0       101.2   176.8   64.8    54.3   
14           1                NaN       103.5   189.0   66.9    55.7   
15           0                NaN       103.5   189.0   66.9    55.7   
16           0                NaN       103.5   193.8   67.9    53.7   
17           0                NaN       110.0   197.0   70.9    56.3   
18           2              121.0        88.4   141.1   60.3    53.2   
19           1               98.0        94.5   155.9   63.6    52.0   
20           0               81.0        94.5   158.8   63.6    52.0   
21           1              118.0        93.7   157.3   63.8    50.8   
22           1              118.0        93.7   157.3   63.8    50.8   
23           1              118.0        93.7   157.3   63.8    50.8   
24           1              148.0        93.7   157.3   63.8    50.6   
25           1              148.0        93.7   157.3   63.8    50.6   
26           1              148.0        93.7   157.3   63.8    50.6   
27           1              148.0        93.7   157.3   63.8    50.6   
28          -1              110.0       103.3   174.6   64.6    59.8   
29           3              145.0        95.9   173.2   66.3    50.2   
..         ...                ...         ...     ...    ...     ...   
175         -1               65.0       102.4   175.6   66.5    53.9   
176         -1               65.0       102.4   175.6   66.5    54.9   
177         -1               65.0       102.4   175.6   66.5    53.9   
178          3              197.0       102.9   183.5   67.7    52.0   
179          3              197.0       102.9   183.5   67.7    52.0   
180         -1               90.0       104.5   187.8   66.5    54.1   
181         -1                NaN       104.5   187.8   66.5    54.1   
182          2              122.0        97.3   171.7   65.5    55.7   
183          2              122.0        97.3   171.7   65.5    55.7   
184          2               94.0        97.3   171.7   65.5    55.7   
185          2               94.0        97.3   171.7   65.5    55.7   
186          2               94.0        97.3   171.7   65.5    55.7   
187          2               94.0        97.3   171.7   65.5    55.7   
188          2               94.0        97.3   171.7   65.5    55.7   
189          3                NaN        94.5   159.3   64.2    55.6   
190          3              256.0        94.5   165.7   64.0    51.4   
191          0                NaN       100.4   180.2   66.9    55.1   
192          0                NaN       100.4   180.2   66.9    55.1   
193          0                NaN       100.4   183.1   66.9    55.1   
194         -2              103.0       104.3   188.8   67.2    56.2   
195         -1               74.0       104.3   188.8   67.2    57.5   
196         -2              103.0       104.3   188.8   67.2    56.2   
197         -1               74.0       104.3   188.8   67.2    57.5   
198         -2              103.0       104.3

In [41]:
test_car = cars_dummy.iloc[4]

test_car

symboling                    2.00
normalized_losses          164.00
wheel_base                  99.40
length                     176.60
width                       66.40
height                      54.30
curb_weight               2824.00
engine_size                136.00
bore                         3.19
stroke                       3.40
compression_ratio            8.00
horsepower                 115.00
peak_rpm                  5500.00
city_mpg                    18.00
highway_mpg                 22.00
price                    17450.00
make_alfa-romero             0.00
make_audi                    1.00
make_bmw                     0.00
make_chevrolet               0.00
make_dodge                   0.00
make_honda                   0.00
make_isuzu                   0.00
make_jaguar                  0.00
make_mazda                   0.00
make_mercedes-benz           0.00
make_mercury                 0.00
make_mitsubishi              0.00
make_nissan                  0.00
make_peugot   

In [57]:
dummy = cars_dummy.values
car = test_car.values
car = car.reshape(1, -1)

dummy
car

array([[2.000e+00, 1.640e+02, 9.940e+01, 1.766e+02, 6.640e+01, 5.430e+01,
        2.824e+03, 1.360e+02, 3.190e+00, 3.400e+00, 8.000e+00, 1.150e+02,
        5.500e+03, 1.800e+01, 2.200e+01, 1.745e+04, 0.000e+00, 1.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 1.000e+00, 0.000e+00,
        1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00,
        0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00]])

In [70]:
KDTree.valid_metrics

['euclidean',
 'l2',
 'minkowski',
 'p',
 'manhattan',
 'cityblock',
 'l1',
 'chebyshev',
 'infinity']

In [66]:
treel1 = KDTree(dummy, metric='l1')                                
distl1, indl1 = treel1.query(car, k=5)
print(indl1)  # indices of 2 closest neighbors
print(distl1)  # distances to 2 closest neighbors

[[  4   6 136 200 104]]
[[  0.   327.4  823.88 955.94 956.47]]


In [ ]:
print(df.loc[[4, 6, 136, 200, 104]])

In [71]:
treeE = KDTree(dummy, metric='euclidean')                                
distE, indE = treeE.query(car, k=5)
print(indE)  # indices of 2 closest neighbors
print(distE)  # distances to 2 closest neighbors

[[  4   6 104 200 136]]
[[  0.         261.53657488 468.08963298 630.49605915 702.02462307]]


In [83]:
print(df.loc[[4,6,104,200,136]])

     symboling  normalized_losses    make fuel_type aspiration num_doors  \
4            2              164.0    audi       gas        std      four   
6            1              158.0    audi       gas        std      four   
104          3              194.0  nissan       gas        std       two   
200         -1               95.0   volvo       gas        std      four   
136          3              150.0    saab       gas      turbo       two   

    body_style drive_wheels engine_location  wheel_base   ...     engine_size  \
4        sedan          4wd           front        99.4   ...             136   
6        sedan          fwd           front       105.8   ...             136   
104  hatchback          rwd           front        91.3   ...             181   
200      sedan          rwd           front       109.1   ...             141   
136  hatchback          fwd           front        99.1   ...             121   

     fuel_system  bore  stroke compression_ratio horsepo

In [78]:
treeMan = KDTree(dummy, metric='l1')                                
distMan, indMan = treeMan.query(car, k=5)
print(indMan)  # indices of 2 closest neighbors
print(distMan)  # distances to 2 closest neighbors

[[  4   6 136 200 104]]
[[  0.   327.4  823.88 955.94 956.47]]


In [79]:
print(df.loc[[4,6,136,200,104]])


     symboling  normalized_losses    make fuel_type aspiration num_doors  \
4            2              164.0    audi       gas        std      four   
6            1              158.0    audi       gas        std      four   
136          3              150.0    saab       gas      turbo       two   
200         -1               95.0   volvo       gas        std      four   
104          3              194.0  nissan       gas        std       two   

    body_style drive_wheels engine_location  wheel_base   ...     engine_size  \
4        sedan          4wd           front        99.4   ...             136   
6        sedan          fwd           front       105.8   ...             136   
136  hatchback          fwd           front        99.1   ...             121   
200      sedan          rwd           front       109.1   ...             141   
104  hatchback          rwd           front        91.3   ...             181   

     fuel_system  bore  stroke compression_ratio horsepo